
package max.retail.stores.ws.gstin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MAXInvoiceDetailsIfc", targetNamespace = "http://gstin.ws.stores.retail.lsipl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MAXInvoiceDetailsIfc {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveInvoiceDetails", targetNamespace = "http://gstin.ws.stores.retail.lsipl/", className = "lsipl.retail.stores.ws.gstin.SaveInvoiceDetails")
    @ResponseWrapper(localName = "saveInvoiceDetailsResponse", targetNamespace = "http://gstin.ws.stores.retail.lsipl/", className = "lsipl.retail.stores.ws.gstin.SaveInvoiceDetailsResponse")
    public String saveInvoiceDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
