
package max.retail.stores.ws.gstin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MAXInvoiceDetailsService", targetNamespace = "http://gstin.ws.stores.retail.lsipl/", wsdlLocation = "http://localhost:7001/GSTInvoice/GSTInvoiceService?wsdl")
public class MAXInvoiceDetailsService
    extends Service
{

    private final static URL MAXINVOICEDETAILSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAXINVOICEDETAILSSERVICE_EXCEPTION;
    private final static QName MAXINVOICEDETAILSSERVICE_QNAME = new QName("http://gstin.ws.stores.retail.lsipl/", "MAXInvoiceDetailsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/GSTInvoice/GSTInvoiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAXINVOICEDETAILSSERVICE_WSDL_LOCATION = url;
        MAXINVOICEDETAILSSERVICE_EXCEPTION = e;
    }

    public MAXInvoiceDetailsService() {
        super(__getWsdlLocation(), MAXINVOICEDETAILSSERVICE_QNAME);
    }

    public MAXInvoiceDetailsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAXINVOICEDETAILSSERVICE_QNAME);
    }

    public MAXInvoiceDetailsService(URL wsdlLocation) {
        super(wsdlLocation, MAXINVOICEDETAILSSERVICE_QNAME);
    }

    public MAXInvoiceDetailsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAXINVOICEDETAILSSERVICE_QNAME);
    }

    public MAXInvoiceDetailsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MAXInvoiceDetailsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MAXInvoiceDetailsIfc
     */
    @WebEndpoint(name = "MAXInvoiceDetailsPort")
    public MAXInvoiceDetailsIfc getMAXInvoiceDetailsPort() {
        return super.getPort(new QName("http://gstin.ws.stores.retail.lsipl/", "MAXInvoiceDetailsPort"), MAXInvoiceDetailsIfc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MAXInvoiceDetailsIfc
     */
    @WebEndpoint(name = "MAXInvoiceDetailsPort")
    public MAXInvoiceDetailsIfc getMAXInvoiceDetailsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gstin.ws.stores.retail.lsipl/", "MAXInvoiceDetailsPort"), MAXInvoiceDetailsIfc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAXINVOICEDETAILSSERVICE_EXCEPTION!= null) {
            throw MAXINVOICEDETAILSSERVICE_EXCEPTION;
        }
        return MAXINVOICEDETAILSSERVICE_WSDL_LOCATION;
    }

}
