
package max.retail.stores.ws.storecredit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MAXStoreCreditWSIfc", targetNamespace = "http://storecredit.ws.stores.retail.max/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MAXStoreCreditWSIfc {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateStoreCreditLockStatus", targetNamespace = "http://storecredit.ws.stores.retail.max/", className = "max.retail.stores.ws.storecredit.UpdateStoreCreditLockStatus")
    @ResponseWrapper(localName = "updateStoreCreditLockStatusResponse", targetNamespace = "http://storecredit.ws.stores.retail.max/", className = "max.retail.stores.ws.storecredit.UpdateStoreCreditLockStatusResponse")
    public boolean updateStoreCreditLockStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "triggerStoreCreditInOldCO", targetNamespace = "http://storecredit.ws.stores.retail.max/", className = "max.retail.stores.ws.storecredit.TriggerStoreCreditInOldCO")
    @ResponseWrapper(localName = "triggerStoreCreditInOldCOResponse", targetNamespace = "http://storecredit.ws.stores.retail.max/", className = "max.retail.stores.ws.storecredit.TriggerStoreCreditInOldCOResponse")
    public int triggerStoreCreditInOldCO(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStoreCreditDetails", targetNamespace = "http://storecredit.ws.stores.retail.max/", className = "max.retail.stores.ws.storecredit.GetStoreCreditDetails")
    @ResponseWrapper(localName = "getStoreCreditDetailsResponse", targetNamespace = "http://storecredit.ws.stores.retail.max/", className = "max.retail.stores.ws.storecredit.GetStoreCreditDetailsResponse")
    public String getStoreCreditDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Boolean arg1);

}
