
package max.retail.stores.ws.storecredit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MAXStoreCreditWSService", targetNamespace = "http://storecredit.ws.stores.retail.max/", wsdlLocation = "http://localhost:7001/StoreCredit/StoreCreditWS?wsdl")
public class MAXStoreCreditWSService
    extends Service
{

    private final static URL MAXSTORECREDITWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAXSTORECREDITWSSERVICE_EXCEPTION;
    private final static QName MAXSTORECREDITWSSERVICE_QNAME = new QName("http://storecredit.ws.stores.retail.max/", "MAXStoreCreditWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/StoreCredit/StoreCreditWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAXSTORECREDITWSSERVICE_WSDL_LOCATION = url;
        MAXSTORECREDITWSSERVICE_EXCEPTION = e;
    }

    public MAXStoreCreditWSService() {
        super(__getWsdlLocation(), MAXSTORECREDITWSSERVICE_QNAME);
    }

   

    public MAXStoreCreditWSService(URL wsdlLocation) {
        super(wsdlLocation, MAXSTORECREDITWSSERVICE_QNAME);
    }

    

    public MAXStoreCreditWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

   

    /**
     * 
     * @return
     *     returns MAXStoreCreditWSIfc
     */
    @WebEndpoint(name = "MAXStoreCreditWSPort")
    public MAXStoreCreditWSIfc getMAXStoreCreditWSPort() {
        return super.getPort(new QName("http://storecredit.ws.stores.retail.max/", "MAXStoreCreditWSPort"), MAXStoreCreditWSIfc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MAXStoreCreditWSIfc
     */
    @WebEndpoint(name = "MAXStoreCreditWSPort")
    public MAXStoreCreditWSIfc getMAXStoreCreditWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://storecredit.ws.stores.retail.max/", "MAXStoreCreditWSPort"), MAXStoreCreditWSIfc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAXSTORECREDITWSSERVICE_EXCEPTION!= null) {
            throw MAXSTORECREDITWSSERVICE_EXCEPTION;
        }
        return MAXSTORECREDITWSSERVICE_WSDL_LOCATION;
    }

}
