
SET COMMON_PATH=..\..\common

SET COMMON_SQL_PATH=%COMMON_PATH%\db\sql
SET COMMON_LIB_PATH=%COMMON_PATH%\lib
SET COMMON_LOGS_PATH=%COMMON_PATH%\logs

rem *** Specific database paths ***
SET COMMON_SYBASE_PATH=%COMMON_PATH%\db\sybase
SET COMMON_DB2_PATH=%COMMON_PATH%\db\db2
SET COMMON_ORACLE_PATH=%COMMON_PATH%\db\oracle
SET COMMON_MYSQL_PATH=%COMMON_PATH%\db\mysql

SET COMMON_LANG=es
SET COMMON_REGION=US
SET COMMON_LOCALE=%COMMON_LANG%_%COMMON_REGION%
SET COMMON_CHARSET=iso_1
SET COMMON_COLLATION=437ESP
