
package max.retail.stores.ws.employee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MAXEmployeeDiscountLimitService", targetNamespace = "http://employee.ws.stores.retail.max/", wsdlLocation = "http://localhost:7001/EmployeeDiscount/EmployeeWS?wsdl")
public class MAXEmployeeDiscountLimitService
    extends Service
{

  //  private final static URL MAXEMPLOYEEDISCOUNTLIMITSERVICE_WSDL_LOCATION;
    private final static URL MAXEMPLOYEEDISCOUNTLIMITSERVICE_WSDL_LOCATION;
    
    private final static WebServiceException MAXEMPLOYEEDISCOUNTLIMITSERVICE_EXCEPTION;
    private final static QName MAXEMPLOYEEDISCOUNTLIMITSERVICE_QNAME = new QName("http://employee.ws.stores.retail.max/", "MAXEmployeeDiscountLimitService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/EmployeeDiscount/EmployeeWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAXEMPLOYEEDISCOUNTLIMITSERVICE_WSDL_LOCATION = url;
        MAXEMPLOYEEDISCOUNTLIMITSERVICE_EXCEPTION = e;
    }

    public MAXEmployeeDiscountLimitService() {
        super(__getWsdlLocation(), MAXEMPLOYEEDISCOUNTLIMITSERVICE_QNAME);
    }

   

    public MAXEmployeeDiscountLimitService(URL wsdlLocation) {
        super(wsdlLocation, MAXEMPLOYEEDISCOUNTLIMITSERVICE_QNAME);
    }

    

    public MAXEmployeeDiscountLimitService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

   

    /**
     * 
     * @return
     *     returns MAXEmployeeDiscountLimitIfc
     */
    @WebEndpoint(name = "MAXEmployeeDiscountLimitPort")
    public MAXEmployeeDiscountLimitIfc getMAXEmployeeDiscountLimitPort() {
        return super.getPort(new QName("http://employee.ws.stores.retail.max/", "MAXEmployeeDiscountLimitPort"), MAXEmployeeDiscountLimitIfc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MAXStoreCreditWSIfc
     */
    @WebEndpoint(name = "MAXEmployeeDiscountLimitPort")
    public MAXEmployeeDiscountLimitIfc getMAXEmployeeDiscountLimitPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://employee.ws.stores.retail.max/", "MAXEmployeeDiscountLimitPort"), MAXEmployeeDiscountLimitIfc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAXEMPLOYEEDISCOUNTLIMITSERVICE_EXCEPTION!= null) {
            throw MAXEMPLOYEEDISCOUNTLIMITSERVICE_EXCEPTION;
        }
        return MAXEMPLOYEEDISCOUNTLIMITSERVICE_WSDL_LOCATION;
    }

}
